name: scale3c_examples
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  provider: ^6.0.5
  flex_color_picker: ^3.0.0
  loading_indicator: ^3.1.0
  loading_animation_widget: ^1.2.0+4
  page_transition: ^2.0.9
  concentric_transition: ^1.0.3
  animations: ^2.0.7
  rive: ^0.10.0
  flutter_zoom_drawer: ^3.0.3
  flutter_advanced_drawer: ^1.3.2
  flutter_slider_drawer: ^2.1.2
  flutter_inner_drawer: ^1.0.0+1
  backdrop: ^0.8.1
  animated_bottom_navigation_bar: ^1.1.0+1
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.1
  # convex_bottom_bar: ^3.1.0+1
  curved_navigation_bar: ^1.0.3
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  flutter_snake_navigationbar: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
